apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc02
  labels:
    app: msvc
    v: 2
spec:
  replicas: 2
  selector:
    matchLabels:
        app: msvc
        v: 2
  template:
    metadata:
      labels:
        app: msvc
        v: 2
    spec:
      containers:
        - image: 168.1.9.1/test/microsvc02:latest
          imagePullPolicy: IfNotPresent
          name: msvc01
          ports:
            - containerPort: 9090
              name: apiport

